### ISSUE TITLE
Webhook for application readiness

### ISSUE THREAD

**Issue by vvvityaaa** [Blueshoe/django-hurricane#9]
HTTP request should be posted, whenever the server has been started and is ready for receiving requests. Event, that triggers webhook is starting of HTTP server, which is only possible after all preliminary commands were executed (e.g. optional management commands). 

Webhook should not block the main event loop of the application, so it should be implemented as an async task on the event of HTTP server start. Post request can be in a form of JSON.

**Comment by Schille** [comment]
I'd say we need another webhook trigger in case of management command failures. It should include the reason and the trace of the exception plus some meta data.
I would suggest a list of new command options in order to specify webhook target URLs. The payload could be of a static message format at the moment which includes relevant data.

**Comment by Schille** [comment]
Thank you for your implementation @vvvityaaa. 
As I looked into the current master I found following misconception: the `LivenessWebhook` is only fired once upon startup. I think the webhook should be moved to the probe handler and trigger upon state changes: `none -> healthy` and `healthy -> unhealthy` and eventually from `unhealthy -> healthy`.

In addition to that, please always add the `hostname` and a `timestamp` to each message.

**Comment by vvvityaaa** [comment]
Thank you for your comments @Schille. I think, the idea of state variables for liveness and readiness-webhooks is very good.
